config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  resources :patients do 
  	resources :visits
  end
  resources :users
  
  root 'static_pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :visits

#Search in Rails From: https://stackoverflow.com/questions/12010780/search-in-rails
#Multiple Search Paramerters
	#def self.search(search)
	  #where("name LIKE ? OR dob LIKE ? OR phone LIKE ?",  "%#{search}%" , "%#{search}%" , "%#{search}%")
	#end
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :patient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index
   #if params[:search] #If search applied
      #@patients = Patient.all.paginate(:per_page => 10, :page => params[:page]).search(params[:search]).order(params[:sort])
    
    #else
      #@patients = Patient.all.paginate(:per_page => 3, :page => params[:page])
    #end

    #if params[:sort]
          #@patients = Patient.order(params[:sort] + " " + params[:direction]).paginate(:per_page => 3, :page => params[:page])
    #end

      @q = Patient.all.ransack(params[:q])
      @patients = @q.result(distinct: true).paginate(:per_page => 3, :page => params[:page])

  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :dob, :address, :phone)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :clinic, :email, :password)
    end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
	def create 
		@patient = Patient.find(params[:patient_id])
		@visit = @patient.visits.create(visit_params) 
		redirect_to patient_path(@patient)
	end

	 def destroy
		 @patient = Patient.find(params[:patient_id])
		 @visit = @patient.visit.find(params[:id])
		 @visit.destroy
		 redirect_to patient_path(@patient)
 	end 

	private 
	def visit_params
		params.require(:visit).permit(:date, :infection, :injury, :observations, :hospital_request, :condition)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
def sortable(column, title = nil)
  title ||= column.titleize
   direction = column == params[:sort] && params[:direction] == "asc" ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Cloud Application Development | 
    Leon Mulvaney | 14445618
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home",   root_path %></li>
      <li><%= link_to "Contact", "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Medical App", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Users",   users_path %></li> <!--Uses Ruby helper link_to  -->
            <li><%= link_to "Patients",   patients_path %></li>
            <li><%= link_to "Log Out", '#' %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all','data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  	<%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form|%>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :patient_name %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.text_field :dob, id: :patient_dob %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :patient_address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :patient_phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<!--Ransack Search Gem From: https://github.com/activerecord-hackery/ransack -->
<h1>Patients</h1>

<div class ="row">

<div class ="col-md-4">
    <%= search_form_for @q do |f| %>
   <%= f.label "Search Patients" %>
  <%= f.search_field :name_or_dob_or_address_or_phone_cont, class: 'form-control input-sm'%>
  <%= f.submit class: 'btn' %>
  <%= link_to "Reset Filter",   patients_path, class: 'btn btn-default' %>
<% end %>
  </div>
  <div class ="col-md-4"></div>
  <div class ="col-md-4"></div>
</div>




<hr>
<table class = "table table-striped table-hover">
  <thead>
    <tr>
      <!-- Sortable columns From: 
      https://github.com/activerecord-hackery/ransack -->
      <th class ="h5"><%= sort_link(@q, :name) %></th>
      <th class ="h5"><%= sort_link(@q, :dob) %></th>
      <th class ="h5"><%= sort_link(@q, :address) %></th>
      <th class ="h5"><%= sort_link(@q, :phone) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody> 
    <% @patients.each do |patient| %> 
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.dob %></td>
        <td><%= patient.address %></td>
        <td><%= patient.phone %></td>
        <td><%= link_to 'View Medical History', patient,  class: 'btn-sm btn-info' %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient), class: 'btn-sm btn-warning' %></td>
        <td><%= link_to 'Remove', patient, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-sm btn-danger'%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= will_paginate @patients %>

<hr>
<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @patient.dob %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>


	<h2>Visits</h2>
	<hr>
	<%= render @patient.visits %> 

	<h2> Add Visit:</h2>
	<%= render 'visits/form' %> 

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
	<div class="center jumbotron">
	  <h1>Welcome to the Medical App</h1>

	  <h2>
	    This is the home page for the
	    Cloud Application Development Project
	  </h2>

	  <%= link_to "Sign in", new_user_path, class: "btn btn-md btn-info" %>
	</div>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :clinic %>
    <%= form.text_field :clinic, id: :user_clinic %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table id ="users">
  <thead>
    <tr>
      <th>Name</th>
      <th>Clinic</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.clinic %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Clinic:</strong>
  <%= @user.clinic %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/visits/_form.html.erb
	<%= form_for([@patient,@patient.visits.build])do |f|  %>
	<p>
		<%= f.label :date, class: "h4" %> <br />
		<%= f.text_field :date , class: "form-control" %>
	</p>

	<p>
		<%= f.label :infection %> <br />
		<%= f.text_field :infection, class: "form-control" %>
	</p>

	<p>
		<%= f.label :injury %> <br />
		<%= f.text_field :injury, class: "form-control" %>
	</p>

	<p>
		<%= f.label :observations %> <br />
		<%= f.text_field :observations, class: "form-control" %>
	</p>

	<p>
		<%= f.label :hospital_request %> <br />
		<%= f.text_field :hospital_request, class: "form-control" %>
	</p>

	<p>
		<%= f.label :condition %> <br />
		<%= f.text_field :condition, class: "form-control" %>
	</p>

	<p>
		<!--Buttons in Rails From: https://stackoverflow.com/questions/26499620/how-to-make-a-rails-form-for-submit-button-a-bootstrap-button -->
		<%= f.submit :Submit, class: 'btn btn-sm btn-success'%>
	</p>
	<% end %>

app/views/visits/_visit.html.erb
	<p>
		<strong>Date:</strong>
		<%= visit.date %>
	</p>

	<p>
		<strong>Infection:</strong>
		<%= visit.infection %>
	</p>

	<p>
		<strong>Injury:</strong>
		<%= visit.injury %>
	</p>

	<p>
		<strong>Observations:</strong>
		<%= visit.observations %>
	</p>

	<p>
		<strong>Hospital Request:</strong>
		<%= visit.hospital_request %>
	</p>

		<p>
		<strong>Condition:</strong>
		<%= visit.condition %>
	</p>
	<hr>